---
- name: Ping Test Play
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Get Hosts List
    tags: first
    set_fact:
      hosts_list: "{{ hosts.split(' ') }}"

  - name: Ping
    tags: first
    icmp_ping: 
      dest: "{{ item }}"
      count: 10
      interval: 1 
      size: 56
      ttl: 64
    with_items:
      - "{{ hosts_list }}"
    register: ping_output

  - name: Render Ping Template
    tags: second
    template:
      src: templates/ping_template.j2
      dest: "{{ workspace }}/config/ping_results.csv"
    vars:
      responseList: "{{ ping_output.results }}"
      probe_name: "{{ lookup('env', 'probeName') }}"
      probe_location: "{{ lookup('env', 'probeLocation') }}"
...
